### ISSUE TITLE
TypeError: label_list() got an unexpected keyword argument 'doc'

### ISSUE THREAD

**Issue by regisd** [bazelbuild/skydoc#112]
I'm trying to add skydoc on my rules, but it fails with this "got an unexpected keyword argument 'doc'". In fact, I can reproduce with any other existing repository

> bazel release 0.18.0
> Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
> [GCC 6.3.0 20170516] on linux2

**Steps**:
```
git clone https://github.com/georgeliaw/rules_wheel.git
cd rules_wheel
bazel build //:wheel-docs
```

**WORKSPACE**
```
git_repository(
    name = "io_bazel_rules_sass",
    remote = "https://github.com/bazelbuild/rules_sass.git",
    tag = "0.0.3",
)
load("@io_bazel_rules_sass//sass:sass.bzl", "sass_repositories")
sass_repositories()

git_repository(
    name = "io_bazel_skydoc",
    remote = "https://github.com/bazelbuild/skydoc.git",
    tag = "0.1.4",
)
load("@io_bazel_skydoc//skylark:skylark.bzl", "skydoc_repositories")
skydoc_repositories()

```

**Comment by regisd** [comment]
Also, it seems the version of the "getting started" is quite outdated https://skydoc.bazel.build/docs/getting_started.html

**Comment by dgoldstein0** [comment]
It sounds like you've discovered that the `doc` param on various attr.<type>() calls isn't supported.  the current expectation of skydoc is that docs come in a comment right after the rule declaration, e.g.

```
foo = rule( ...
)
""" docs go here""
```

but I would love it if we had support for `doc` parameters.  A bunch of my rules share some of their attrs, and we end up documenting these multiple times at the moment since we need the docs after every rule; even though we've deduped the actual attr declaration by declaring some dicts that we reuse like `attrs = dict(_some_attrs.items() + _other_attrs.items())`
