### ISSUE TITLE
Stardoc doesn't fail the build on DocstringParseException

### ISSUE THREAD

**Issue by jerechua** [bazelbuild/skydoc#121]
Currently Stardoc logs these errors to stderr. On the first build you do see these errors, but subsequent builds are cached and you don't see the errors again which fails silently.

**Comment by c-parsons** [comment]
I think this "feature" was designed to continue generating documentation for rules which don't trigger parse exceptions, even if one docstring in the build is invalid.

I would indeed be up for re-evaluating that decision -- perhaps it's best to fail loudly when any documentation would otherwise be dropped.

**Comment by jerechua** [comment]
My expectation was that since I explicitly tell Stardoc which functions I want extracted, I want to make sure they're actually extracted.

If the failure mode of completely failing the build is too harsh, what if there was a "strict" mode (or some other name) where the rule fails if any documentation was dropped?

**Comment by laurentlb** [comment]
I'd prefer Stardoc to be strict, and fail in case of issue.

When there's a failure, it shouldn't be hard for the owner to update the file. If they can't, they may instead give the list of functions they care about.
