### ISSUE TITLE
Support for release versions or version numbers

### ISSUE THREAD

**Issue by Profpatsch** [bazelbuild/skydoc#141]
https://docs.bazel.build started versioning their docs, like

```
https://docs.bazel.build/versions/master/best-practices.html#bazelrc
https://docs.bazel.build/versions/0.19.1/best-practices.html#bazelrc
https://docs.bazel.build/versions/0.21.0/best-practices.html#bazelrc
```

This ensures it is possible to create stable references to the documentation.

It would be nice if stardoc would provide such a feature by default as well, or at least have a way to prominently display the current version the user is looking at (then such a multi-version docserver can be implemented quite easily).

Refiled from https://github.com/tweag/rules_haskell/issues/543

**Comment by c-parsons** [comment]
Generating multiple versions of documentation with one execution of Stardoc is quite a bit outside the scope of what Stardoc currently supports. That said, I could this be handled by writing your own custom output templates -- you could generate custom output templates with your current version number so that generated links (etc) match the version number you'd like.

Alternatively, you can access Stardoc's raw proto output and, from that, manage your own rendering / hosting solution.

I think this FR is best closed as "infeasible" at this point as for a canonical solution.
