### ISSUE TITLE
Explicit format for docstring formatting

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/skydoc#183]
There's some ambiguity around docstring formatting: how may a doc writer specify formatting in docstrings so that Stardoc behaves well for all output formats?

For example, which of the following is appropriate:

```
my_rule = rule(
    implementation = my_rule_impl,
    doc = "This is **my** rule. It does stuff.",
)
```

OR

```
my_rule = rule(
    implementation = my_rule_impl,
    doc = "This is <b>my</b> rule. It does stuff.",
)
```

The same confusion applies for links and newlines -- what's appropriate?

**Comment by laurentlb** [comment]
What do other tools do (in other languages)?

**Comment by alexeagle** [comment]
Which are currently supported?

rules_nodejs has a bunch of documentation using markdown in docstrings, that works with skydoc. e.g. this is html-escaped: https://github.com/bazelbuild/rules_nodejs/blob/master/docs/rollup/rollup_bundle.html#L457
and this shows code in backticks rendered in fixed-width
https://bazelbuild.github.io/rules_nodejs/npm_package/npm_package.html#npm_package

After changing to skydoc this is all producing html with backticks still present, and the lack of escaping makes it totally broken
https://alexeagle.github.io/rules_nodejs/Built-ins.html

**Comment by c-parsons** [comment]
In terms of bracket escaping, is this not fixed even with https://github.com/bazelbuild/skydoc/pull/212 ?

**Comment by alexeagle** [comment]
Good question. This is why I commented on https://github.com/bazelbuild/skydoc/commit/9283f6a44811423756ab898e98ce410029c12f7b#comments - I didn't go past that commit since it introduces more transitive deps.

So if I do go all the way to HEAD and pick up the fix for #212 it is still producing docs with unescaped angle brackets, because my markdown appears in the attribute doc, and that fix only touched the doc for the rule.
https://github.com/bazelbuild/skydoc/pull/212/files#diff-8bf5a2d5828008f425ab540e88c288e5R27 seems to be the spot that was missed.

**Comment by c-parsons** [comment]
That "spot that was missed" was an intentional omission.
The short explanation is that the current format has attribute documentation in table cells, which, for the github markdown renderer, display markdown in raw form (backticks, for example, are displayed as actual backticks, and don't denote code)
We thus avoid escaping the angle brackets in attribute documentation so that there's *a* way to do formatting in these strings. For example it would otherwise be impossible to use `<code>` tags.

See https://github.com/bazelbuild/skydoc/issues/69 for a longer explanation here.

So, would your preferred fix be that you can use markdown-style formatting in your docstrings, and that all other XML tags (i.e. all angle brackets) in your docstrings are escaped?

**Comment by alexeagle** [comment]
My naive answer is that I'd like all the docs I wrote for skydoc to still work with stardoc. We have a fair amount of docs, and this didn't get a mention on the deprecation page https://skydoc.bazel.build/docs/skydoc_deprecation.html so I was a bit surprised it changed.

Even if I didn't have a corpus of existing docs, I'd still rather use markdown in the attribute docstring just because it's familiar from most other textareas like GitHub comments that render markdown. But I guess having a consistent format is more important than which format it is, and it would only take me an hour to reformat all our existing docs.

**Comment by c-parsons** [comment]
The easiest fix given the Stardoc capabilities at HEAD would likely be to create output templates which don't use pure HTML tables, and escape angle brackets from all doc strings -- that way, your github pages will respect the markdown formatting and all angle brackets will be escaped.

I've opened https://github.com/bazelbuild/skydoc/issues/216 to track this.

**Comment by c-parsons** [comment]
The recommendation is now that users use markdown_tables templates, and their docstring formatting is markdown-style.
