### ISSUE TITLE
Allow stubbing out some transitive dependencies

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/skydoc#185]
It would be nice if Stardoc was able to function without having the full transitive set of bzl files available (as not all of them are relevant in Stardoc's processing; Stardoc only needs approximately "loading phase" evaluation of the Starlark code)

A couple of options:

1.  When missing an import, Stardoc could automatically attempt to fake any import symbols (using a nicemock equivalent)
2. We could allow a user to specify the labels of bzl files they would prefer to stub out instead of actually loading.

This might make for easier adoption in cases where `bzl_libary` targets are not created for one's transitive dependencies.

**Comment by adam-azarchs** [comment]
A probably particularly-common example of where this would be helpful is for documenting rules that depend on stuff in `bazel_tools`, for for example `@bazel_tools//tools/build_defs/pkg:pkg.bzl`, since that does not export a `bzl_library`, and the only target that seems to make that file visible is `@bazel_tools//tools:srcs`, which is broken right now (depending on targets which do not exist).

**Comment by c-parsons** [comment]
Indeed (might help fix #166)

**Comment by tmc** [comment]
@adam-azarchs is there an issue open for the `@bazel_tools//tools:srcs` issue?

**Comment by adam-azarchs** [comment]
Not that I am aware of, unless you count #166.

**Comment by laurentlb** [comment]
Is there any way to make `@bazel_tools` available?

**Comment by c-parsons** [comment]
This is not fixed in an ideal manner, as of yet, but will have a decent workaround with the next bazel release:

Add `@bazel_tools//tools:bzl_srcs` to the dependencies of your `bzl_library` target.
