### ISSUE TITLE
Provide a workflow for documenting all public symbols in multiple files

### ISSUE THREAD

**Issue by brandjon** [bazelbuild/skydoc#208]
The best practice workaround for #207 is to explicitly re-export every symbol that you want to be documented. This is error-prone because it's very easy to add code and documentation for a new symbol but forget to update the exports in the hub bzl. Ideally we should support the use case of "Include documentation for all public symbols in the following files...".

In the `stardoc` rule this would essentially mean replacing the `input` label attr with a `srcs` (or `inputs`) label_list attr. The stardoc binary would run on each of these input files and concatenate the result into a single markdown file.

(+@c-parsons from offline discussion.)

**Comment by brandjon** [comment]
Also, the `srcs` or `inputs` attribute could possibly accept a target providing `StarlarkLibraryInfo` in place of plain bzl files. This would allow documenting all the direct `srcs` of a `bzl_library` without duplicating the list in the stardoc rule.

**Comment by brandjon** [comment]
And it would also avoid needing to specify deps of the .bzl, since that'd also be available from the provider.

**Comment by c-parsons** [comment]
@brandjon and I discussed this offline, and can agree that this is not worth it at this time.

Currently "one target" = "one input" -> "one output" works fairly well, given that there are some tough issues to resolve for the "multiple inputs" use case (for example, the documentation doesn't give information about which file to load the symbol from. Another example: what if multiple files export the same symbol for different locations?)

The example https://github.com/bazelbuild/skydoc/issues/207 is indeed broken, and I think the solution of re-exporting symbols imported in a single hub file is not to just workaround stardoc "limitations" but so that users can load these documented symbols from a single bzl file. That way each stardoc output also corresponds to a single API "entry point".

Feel free to add on to the description, Jon. Otherwise, I'm closing this unless we see some other use case we haven't thought of :)
