### ISSUE TITLE
Use pure markdown templates as default output format

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/skydoc#227]
This is a proposal which I'd like to submit for feedback. Without significant objections, I plan to go forward.

**Summary**
Make the `pure_markdown` templates introduced in https://github.com/bazelbuild/skydoc/commit/33e81298ffc1af67cdb4085b1ea678be26b322cc the new default, and deprecate the old default template format.

As a tie-in to https://github.com/bazelbuild/skydoc/issues/183, also always recommend that users use markdown formatting constructs to format their docstrings.

**Reasoning**
There are a number of related bugs to reconciling formatting compatible with the HTML tables in Stardoc's default output: https://github.com/bazelbuild/skydoc/issues/69, 
https://github.com/bazelbuild/skydoc/issues/216.
In short summary, HTML table cells (used to show parameter/attribute docstrings) do not respect typical markdown formatting constructs. Attempting to bold a word using `**bold**`, for example, would display:

<table class="params-table">
  <colgroup>
    <col class="col-param" />
    <col class="col-description" />
  </colgroup>
  <tbody>
    <tr id="bracket_function-name">
      <td><code>my_arg</code></td>
      <td>
        required.
        <p>
          an arg with **formatted** docstring.
        </p>
      </td>
    </tr>
  </tbody>
</table>

There are ways around this, but none are ideal (for example, using html tags, but this should be discouraged. See https://github.com/bazelbuild/skydoc/issues/183)

By using pure markdown tables (with some minor tricks to support multi-line table cells, see https://github.com/bazelbuild/skydoc/issues/69#issuecomment-518786516) we can universally recommend that users use markdown-formatting for their docstrings, and institute HTML-tag escaping on docstrings.

**Caveats**
1. Changing default output templates means we may break some users, though they can always retain backward compatibility by forking the old default templates and using them as "custom" templates.

2. Users who are still using old HTML-style formatting tags such as `<b>` will need to migrate.

3. The new output format is a bit different (and thus may appeal less to some users) in some ways, though I'd argue the formats are comparable. See https://github.com/bazelbuild/skydoc/issues/69#issuecomment-441771439 for a discussion of table display.

**Comment by laurentlb** [comment]
LGTM. Let's use markdown in docstrings and no HTML.

**Comment by jin** [comment]
> Changing default output templates means we may break some users, though they can always retain backward compatibility by forking the old default templates and using them as "custom" templates.

Let's roll a new major version (1.0.0?) and indicate this change in the release notes.

The proposal SGTM, we should converge on markdown docs everywhere.

**Comment by c-parsons** [comment]
> Let's roll a new major version (1.0.0?) and indicate this change in the release notes.

I agree. I think this is an important change to gate on a major version.

**Comment by brandjon** [comment]
As I understand from offline discussion with Chris:

1) The new ("pure") template has uniform escaping behavior across all kinds of documentation fields. That is, `a < b` and `<b>emphasis</b>` render the same no matter where they occur.

2) This behavior is to always do escaping, so `a < b` renders literally (as desired), and `<b>emphasis</b>` also renders literally (as not desired).

3) Because `<br>` renders literally, it can no longer be used to embed newlines in table cells. This means an existing use case is broken by making the pure template the new default. The workaround for users is to opt back into the old template and continue to write `<br>` in their docstrings. The longer term solution is for us to add special newline-to-`<br>` processing behavior in the renderer, so that users would not need to use `<br>` at all in their strings.

So the upside of this change is that we can make the uniform recommendation that Starlark documentation be written in Markdown, sans inline HTML. This is a win and IMO worth the immediate breakage for some users.

>> Let's roll a new major version (1.0.0?) and indicate this change in the release notes.
>
> I agree. I think this is an important change to gate on a major version.

Let's not roll 1.0.0 until at least the repo is renamed to "bazelbuild/stardoc". There's no requirement to associate important changes with major version bumps (or any version bumps) prior to 1.0.0 anyway.

I'd be cautious about the 1.0.0 bump, since *every* breaking change from that point on will require further bumps, which implies either a slow release schedule, a slow rate of changes, or a large number of major versions.

**Comment by jin** [comment]
> Let's not roll 1.0.0 until at least the repo is renamed to "bazelbuild/stardoc". There's no requirement to associate important changes with major version bumps (or any version bumps) prior to 1.0.0 anyway.

Let's do that - @c-parsons, would you like me to help with repo renaming? I've done this once with gmaven_rules -> rules_jvm_external and broke some things along the way, and can help prevent them for this repo.

> I'd be cautious about the 1.0.0 bump, since every breaking change from that point on will require further bumps, which implies either a slow release schedule, a slow rate of changes, or a large number of major versions.

Ensuring that we bump the major version every time we make a breaking change keeps us honest and communicates change management to our users implicitly. 

It may actually be a good thing that major versions are rolled out slowly, because we shouldn't be releasing breaking changes to our software all the time. We have to be careful about such changes.

I also don't see a problem with a large number of major versions - it just means that the software has evolved quickly, but one can ensure a stable use case within each major version.

**Comment by c-parsons** [comment]
> Let's do that - @c-parsons, would you like me to help with repo renaming? I've done this once with gmaven_rules -> rules_jvm_external and broke some things along the way, and can help prevent them for this repo.

That would be excellent :) https://github.com/bazelbuild/skydoc/issues/187 for tracking.

> Let's not roll 1.0.0 until at least the repo is renamed to "bazelbuild/stardoc". There's no requirement to associate important changes with major version bumps (or any version bumps) prior to 1.0.0 anyway.

I would agree this is necessary but not sufficient for the 1.0.0 tag.

**Comment by brandjon** [comment]
Another milestone for blocking 1.0 should be the removal of skydoc, I suppose.
