### ISSUE TITLE
Markdown output seems broken, is mostly HTML

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/skydoc#69]
With tag 0.1.4 of skydoc, and `skylark_doc(format="markdown")` I am getting output that's mostly HTML with a few markdown-looking headers:

```
<!---
Documentation generated by Skydoc
-->
<h1>jasmine_node_test Rules</h1>


<nav class="toc">
  <h2>Macros</h2>
  <ul>
    <li><a href="#jasmine_node_test">jasmine_node_test</a></li>
  </ul>
</nav>
<a name="jasmine_node_test"></a>
## jasmine_node_test

<pre>
jasmine_node_test(<a href="#jasmine_node_test.name">name</a>, <a href="#jasmine_node_test.srcs">srcs</a>, <a href="#jasmine_node_test.data">data</a>, <a href="#jasmine_node_test.deps">deps</a>)
</pre>




<a name="jasmine_node_test_args"></a>
### Attributes
```

**Comment by hsyed** [comment]
@jin (hoping you are the one to ping for this)

Two specific fixes to the generated markdown -- I'm not am markdown expert and I known even less about embedding html in markdown but here are specific bugs:

```
<a name="jasmine_node_test_args"></a> 
> NEW LINE NEEDED HERE OR HTML BLOCK CONTINUES<
### Attributes
```

```
<tbody>
    <tr> 
        <td>
            <a href="/kotlin/kotlin_repositories.html#kotlin_repositories">
                <code>kotlin_repositories</code>
            </a>
        </td>
        <td>
            <p>Setup the kotlin rules repositories in a workspace.</p>
 > NEW SPACE SHOULD NOT BE PRESENT HERE - IT BREAKS THE HTML BLOCK<
        </td>
    </tr>
</tbody>   
```

**Comment by jin** [comment]
@davidzchen please take a look?

**Comment by alexeagle** [comment]
Is there a reason there needs to be any HTML in the markdown docs at all? It's hard to read and might not render well depending on where the markdown is hosted/rendered (eg. under Jekyll for github pages)

**Comment by c-parsons** [comment]
FYI @laurentlb 

I'm hijacking this old bug a bit because it remains an issue even with Stardoc (the imminent Skydoc rewrite). Stardoc still generates mostly HTML instead of pure markdown, namely to format attribute tables appropriately.

The solution to this is not straightforward, namely because *pure* markdown tables are not very powerful. There are two limitations to consider:

## 1. Cells of markdown tables cannot handle multline input without HTML tags

For example, 
```
| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell <br> `Line Two` |
```

becomes:

| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell <br> `Line Two` |

but if the `<br>` tag is replaced with a newline character, the table breaks.

## 2. Markdown tables can only handle a consistent number of columns per row, and require header columns.

It's thus impossible to do either of these without HTML `<table>`:

<table>
  <tbody>
    <tr>
      <td>Entry1</td>
      <td>Value1</td>
    </tr>
    <tr>
      <td>Entry2</td>
      <td>Value2</td>
    </tr>
 </tbody>
 </table>

<table>
  <tbody>
    <tr><td colspan="2"><b>Attributes</b></td></tr>
    <tr>
      <td>Entry1</td>
      <td>Value1</td>
    </tr>
    <tr>
      <td>Entry2</td>
      <td>Value2</td>
    </tr>
 </tbody>
 </table>

## Conclusions

(1) is perhaps solvable with care. We could post-process docstrings to convert newline characters to `<br>`.
(2), however, is not quite possible as-is...  but perhaps it is not that important. We could simply enforce we have a tiny header in attribute tables:

| Attribute | Description |
| ------------- | ------------- |
| `name`  | A unique name for this target. |
| `deps` |  A list of dependencies which this target depends on. |

**Comment by jjudd** [comment]
I don't know enough about reStructuredText to know if it would totally solve this issue, but GitHub supports displaying it. [rules_go ](https://github.com/bazelbuild/rules_go) seems to have migrated to entirely rst based documentation rather than Markdown.

Is it worth considering supporting reStructuredText instead of Markdown, provided it solves the issues we're running into with Markdown?

**Comment by alexeagle** [comment]
reStructuredText does support simple tables with no header
https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#simple-tables
and colspans
https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#multicells-table-second-method

I'm currently hosting my site on GitHub Pages,. so for my purposes I want the simplest thing that takes .bzl files and makes a working `/docs` folder. Seems that .rst files have to be preprocessed before they can be served by GitHub Pages?

**Comment by c-parsons** [comment]
@blossommojekwu As discussed offline, one of the major issues with using pure-markdown (no html tag) tables is highlighted above: "Cells of markdown tables cannot handle multline input without HTML tags"

If we had a util function (in MarkdownUtil) to convert line breaks to <br> tags, this would no longer be an issue!

**Comment by brandjon** [comment]
It's not clear to me what the proposed solution is here.

1) What exactly would the table look like from the user's POV? Would it be this?

```python
def foo():
    """My docstring with a table.
    
    | Header left | Header right      |
    | ------------| ----------------- |
    | row1 left   | row1 right        |
    | row2 left   | row2 right top    |
                    row2 right bottom |
    | row3 left   | row3 right        |
    """
```

2) If newlines are converted to `<br>`, I take it this would be a preprocessing step before any markdown rendering is done (since the renderer emits markdown as its final product). But in order to know which newlines to convert to `<br>`, the renderer would have to do its own parsing of the table format. It sounds non-trivial to get this to match the true markdown processor's semantics.

In the short term, I think having the user continue to write HTML `<br>` tags is the way to go, rather than implementing new semantics that deviate from existing tools/standards. In the longer term, it'd be good if the renderer could incorporate its own markdown processor so it can apply transformations like this one in a consistent way (even if the final thing it emits is still markdown and not HTML).

**Comment by clintharrison** [comment]
+1 on this being a pain point for us. We publish our Stardoc content to Confluence with [sphinxcontrib-confluencebuilder](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/) which strips out HTML (yeah, it's a convoluted process).

As a workaround, I wrote a pretty quick & dirty reStructuredText renderer using the Stardoc protobuf output -- https://gist.github.com/clintharrison/2c51a1ad1b739e793721fe7c1b4b0fda. This does mean the `doc` strings need to be reStructuredText instead of Markdown, but otherwise has worked well for us.

**Comment by c-parsons** [comment]
> 1. What exactly would the table look like from the user's POV? Would it be this?
> 
> ```python
> def foo():
>     """My docstring with a table.
>     
>     | Header left | Header right      |
>     | ------------| ----------------- |
>     | row1 left   | row1 right        |
>     | row2 left   | row2 right top    |
>                     row2 right bottom |
>     | row3 left   | row3 right        |
>     """
> ```
>

I'm not sure we have to solve the use case of users trying to include multiline tables as part of their docstrings. The proposal was:

A. Create markdown-only (non HTML) templates 
B. Solve multi-line attribute/parameter docstrings in these templates. That is, for example, turn:

```
my_rule = rule(implementation = ...,
    attrs = { "foo" : attr.label(doc = "'''Line one.
Line two.
Line three.""")})
```

into:

| Attributes | Description |
| ------------- | ------------- |
| name  | The name of the target  |
| foo  | Line one.<br>Line two.<br>Line three. |

Which looks like:

```
| Attributes | Description |
| ------------- | ------------- |
| name  | The name of the target  |
| foo  | Line one.<br>Line two.<br>Line three. |
```

If we don't convert newlines to <br> tags within table cells, the multiline table cell above will appear incorrect.

I don't think we necessarily need to solve this here for every use case and every markdown renderer -- but the proposal here produces "pure" markdown (okay, except for `<br>` tags which are not actually added by the user).... which works specifically for github pages. It also does not require the docstring writer to write HTML tags in their docstrings; only newlines and markdown formating is required.
